export const CATEGORIES = [
  "Banking Jobs",
  "Government Jobs",
  "Defence Jobs",
  "Field Executive Jobs",
  "Sales Jobs",
  "Customer Service Jobs",
  "Team Leader Jobs",
  "Agriculture Jobs",
  "Data Entry Jobs",
  "Freshers Jobs",
  "Experienced Jobs",
];

export const PHOTOS = {
  hero: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1600&q=80",
  office1: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1400&q=80",
  office2: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=80",
  office3: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1400&q=80",
  office4: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=80",
  office5: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1400&q=80",
  office6: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=80",
  meeting: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1400&q=80",
  classroom: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1400&q=80",
  coding: "https://images.unsplash.com/photo-1498050108183-d9cba0ea9f6d?auto=format&fit=crop&w=1400&q=80",
  marketing: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=80",
  study: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1400&q=80",
  recruiter: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80",
  maya: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
  james: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80",
  priya: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
  blog1: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
  blog2: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
  blog3: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
};

export type DemoJob = {
  _id: string;
  title: string;
  slug: string;
  company?: {
    name: string;
    slug: string;
    logo: string;
    industry: string;
    location: string;
    verified: boolean;
    employees: number;
    coverImage?: string;
    about?: string;
  };
  category: string;
  employmentType: string;
  workplace: string;
  experience: string;
  minSalary: number;
  maxSalary: number;
  currency: string;
  location: string;
  featured: boolean;
  urgent: boolean;
  skills: string[];
  createdAt: string;
  applicationsCount: number;
  responsibilities: string;
  requirements: string;
  benefits: string;
  department: string;
  vacancies: number;
};

export const DEMO_JOBS: DemoJob[] = [
  {
    _id: "1",
    title: "Seva Sarthi",
    slug: "seva-sarthi-sbi-pan-india",
    company: {
      name: "Asian Hawks Manpower Services Pvt. Ltd.",
      slug: "asian-hawks-manpower-services",
      logo: "/logo.png",
      industry: "Banking",
      location: "Pan India",
      verified: true,
      employees: 500,
      coverImage: PHOTOS.office1,
      about: "Hiring for SBI branch support roles across India through Asian Hawks Manpower Services Pvt. Ltd.",
    },
    category: "Customer Service Jobs",
    employmentType: "Full Time",
    workplace: "Onsite",
    experience: "Minimum 1 Year",
    minSalary: 20000,
    maxSalary: 20000,
    currency: "INR",
    location: "Pan India",
    featured: true,
    urgent: false,
    skills: ["Communication Skills", "Customer Handling", "Basic Computer Knowledge", "Professional Behaviour"],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    applicationsCount: 18,
    department: "SBI Branch Support",
    vacancies: 25,
    responsibilities: "Assist customers inside SBI branches, help with account opening and documentation, guide customers for YONO and digital banking, support senior citizens and differently-abled customers, maintain branch discipline, coordinate with branch staff, and ensure quality customer service.",
    requirements: "Graduate. Minimum 1 year experience preferred. Freshers may apply as per some requirements.",
    benefits: "₹20,000 CTC per month.",
  },
  {
    _id: "2",
    title: "Team Leader",
    slug: "team-leader-sbi-pan-india",
    company: {
      name: "Asian Hawks Manpower Services Pvt. Ltd.",
      slug: "asian-hawks-manpower-services",
      logo: "/logo.png",
      industry: "Banking",
      location: "Pan India",
      verified: true,
      employees: 500,
      coverImage: PHOTOS.office2,
      about: "Leadership hiring for SBI field projects including ATM Mitra, FOS Collection, FOS Agri, and Seva Sarthi.",
    },
    category: "Team Leader Jobs",
    employmentType: "Full Time",
    workplace: "Onsite",
    experience: "Minimum 2 Years",
    minSalary: 25000,
    maxSalary: 25000,
    currency: "INR",
    location: "Pan India",
    featured: true,
    urgent: true,
    skills: ["Team Handling", "Reporting", "Recruitment", "Training", "Branch Coordination"],
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    applicationsCount: 41,
    department: "ATM Mitra / FOS Collection / FOS Agri / Seva Sarthi",
    vacancies: 12,
    responsibilities: "Lead field teams, achieve targets, coordinate with SBI branches, conduct reviews, recruit and train team members, ensure reporting and compliance, and improve team productivity.",
    requirements: "Graduate with minimum 2 years experience.",
    benefits: "₹25,000 CTC.",
  },
  {
    _id: "3",
    title: "Collection Executive",
    slug: "collection-executive-sbi-multi-location",
    company: {
      name: "Asian Hawks Manpower Services Pvt. Ltd.",
      slug: "asian-hawks-manpower-services",
      logo: "/logo.png",
      industry: "Banking",
      location: "Indore / Ratlam / Vijayawada / Ujjain / Dhar / Eluru",
      verified: true,
      employees: 500,
      coverImage: PHOTOS.office3,
      about: "Collection hiring for SBI-aligned recovery and follow-up work across multiple cities.",
    },
    category: "Field Executive Jobs",
    employmentType: "Full Time",
    workplace: "Onsite",
    experience: "6 Months - 3 Years",
    minSalary: 22000,
    maxSalary: 22000,
    currency: "INR",
    location: "Indore, Ratlam, Vijayawada, Ujjain, Dhar, Eluru + nearby",
    featured: true,
    urgent: false,
    skills: ["EMI Collection", "Customer Follow-up", "Recovery Visits", "Daily Reporting", "Target Achievement", "Branch Coordination"],
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    applicationsCount: 9,
    department: "Collection",
    vacancies: 18,
    responsibilities: "Handle EMI collection, customer follow-up, recovery visits, daily reporting, target achievement, and branch coordination.",
    requirements: "Graduate. 6 months to 3 years experience. Freshers can also apply.",
    benefits: "₹22,000 NTH, PF, ESIC, travel allowance, and incentives.",
  },
  {
    _id: "4",
    title: "ATM Mitra - Field Executive",
    slug: "atm-mitra-field-executive-sbi-pan-india",
    company: {
      name: "Asian Hawks Manpower Services Pvt. Ltd.",
      slug: "asian-hawks-manpower-services",
      logo: "/logo.png",
      industry: "Banking",
      location: "Pan India",
      verified: true,
      employees: 500,
      coverImage: PHOTOS.office4,
      about: "ATM field operations project supporting SBI ATM upkeep and reporting.",
    },
    category: "Field Executive Jobs",
    employmentType: "Full Time",
    workplace: "Onsite",
    experience: "Freshers Welcome",
    minSalary: 23000,
    maxSalary: 23000,
    currency: "INR",
    location: "Pan India",
    featured: true,
    urgent: false,
    skills: ["ATM Inspection", "Reporting", "Geo-tagging", "Issue Coordination"],
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    applicationsCount: 22,
    department: "ATM Mitra",
    vacancies: 30,
    responsibilities: "Visit SBI ATMs, inspect ATM condition, check cleanliness, verify ATM functionality, upload reports, geo-tag photos, and coordinate issue resolution.",
    requirements: "Graduate.",
    benefits: "₹23,000 CTC.",
  },
  {
    _id: "5",
    title: "ATM Mitra - Field Supervisor",
    slug: "atm-mitra-field-supervisor-sbi-pan-india",
    company: {
      name: "Asian Hawks Manpower Services Pvt. Ltd.",
      slug: "asian-hawks-manpower-services",
      logo: "/logo.png",
      industry: "Banking",
      location: "Pan India",
      verified: true,
      employees: 500,
      coverImage: PHOTOS.office5,
      about: "Supervisory role for SBI ATM Mitra field teams.",
    },
    category: "Team Leader Jobs",
    employmentType: "Full Time",
    workplace: "Onsite",
    experience: "Minimum 2 Years",
    minSalary: 25000,
    maxSalary: 25000,
    currency: "INR",
    location: "Pan India",
    featured: true,
    urgent: true,
    skills: ["Team Supervision", "Field Audits", "Reporting", "Training"],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    applicationsCount: 14,
    department: "ATM Mitra",
    vacancies: 10,
    responsibilities: "Supervise field executives, track inspections, audit field work, train new employees, and submit reports.",
    requirements: "Graduate with field supervision experience preferred.",
    benefits: "₹25,000 CTC.",
  },
  {
    _id: "6",
    title: "KCC Agriculture Loan Officer",
    slug: "kcc-agriculture-loan-officer-pan-india",
    company: {
      name: "Asian Hawks Manpower Services Pvt. Ltd.",
      slug: "asian-hawks-manpower-services",
      logo: "/logo.png",
      industry: "Agriculture Finance",
      location: "Pan India",
      verified: true,
      employees: 500,
      coverImage: PHOTOS.office6,
      about: "Field sales hiring for KCC agriculture loan outreach across India.",
    },
    category: "Agriculture Jobs",
    employmentType: "Full Time",
    workplace: "Onsite",
    experience: "Freshers Welcome",
    minSalary: 19500,
    maxSalary: 19500,
    currency: "INR",
    location: "Pan India",
    featured: false,
    urgent: false,
    skills: ["Loan Lead Generation", "Farmer Visits", "Document Collection", "Sales Targets"],
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    applicationsCount: 60,
    department: "Agriculture Loan Sales",
    vacancies: 20,
    responsibilities: "Generate loan leads, visit farmers, explain KCC loans, collect documents, coordinate loan processing, and achieve sales targets.",
    requirements: "12th Pass / Graduate. Freshers welcome.",
    benefits: "₹19,500 CTC, ₹200 daily TA, ₹300 mobile allowance, and performance incentives.",
  },
  {
    _id: "7",
    title: "Data Entry Operator",
    slug: "data-entry-operator-indian-army-jalandhar-cantt",
    company: {
      name: "Asian Hawks Manpower Services Pvt. Ltd.",
      slug: "asian-hawks-manpower-services",
      logo: "/logo.png",
      industry: "Defence",
      location: "Jalandhar Cantt",
      verified: true,
      employees: 500,
      coverImage: PHOTOS.meeting,
      about: "Deployment support role for Indian Army back-office documentation work in Jalandhar Cantt.",
    },
    category: "Defence Jobs",
    employmentType: "Full Time",
    workplace: "Onsite",
    experience: "Freshers Welcome",
    minSalary: 28000,
    maxSalary: 28000,
    currency: "INR",
    location: "Jalandhar Cantt",
    featured: true,
    urgent: false,
    skills: ["Data Entry", "Documentation", "MS Office", "Record Management"],
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    applicationsCount: 11,
    department: "Indian Army Support",
    vacancies: 4,
    responsibilities: "Handle data entry, documentation, record management, MS Office work, daily reports, and confidential records.",
    requirements: "12th Pass.",
    benefits: "₹28,000 CTC.",
  },
];

export const DEMO_BLOGS = [
  {
    title: "How to write a job post people finish reading",
    slug: "write-a-job-post-people-finish",
    excerpt: "Salary, team, and interview steps belong in the first screen.",
    category: "Hiring",
    author: "Northline Editorial",
    coverImage: PHOTOS.blog1,
    createdAt: "2026-07-12",
    content:
      "A complete job post states compensation, the hiring manager, and the interview plan before anyone is asked for a resume.",
  },
  {
    title: "Scorecards hiring managers will actually fill in",
    slug: "scorecards-hiring-managers-use",
    excerpt: "Four questions and one recommendation. Longer forms get abandoned.",
    category: "Interviews",
    author: "Priya Shah",
    coverImage: PHOTOS.blog2,
    createdAt: "2026-06-28",
    content:
      "Keep scorecards short. Ask for evidence against the role, a hire/no-hire call, and one risk.",
  },
  {
    title: "Preparing for a recruiter conversation",
    slug: "preparing-recruiter-conversation",
    excerpt: "Bring range, timeline, and two examples of work.",
    category: "Candidates",
    author: "James Okonkwo",
    coverImage: PHOTOS.blog3,
    createdAt: "2026-06-04",
    content:
      "Candidates who know their salary range and start date move further, faster.",
  },
];
